name: Heavycoin
markdown: redcarpet
pygments: true
BMbroadcastAddr: BM-2cV6qRmeK677qYBetTMXmVmu6vGo3Pn4GG
BMKeccak: BM-NBuu8hBFdnqAeKs42Yg7nftB3QLfJ8ra
BMNomisugi: BM-NBAsCmCqUYR8eaXgs8zebDNPw5rUyM1z
BMMumbly: BM-2cToG5CtGpcGA4Nem3UW1Wt9oj5qGh5mJJ
HVCIPOAddr: 19VzBYvffPj4JcJM6ieNBXLEY9dJBQ2oXa
BTTPREANN: https://bitcointalk.org/index.php?topic=470391
BTTANN: https://bitcointalk.org/index.php?topic=506774
BTTINFO: https://bitcointalk.org/index.php?topic=506774
twitterurl: http://twitter.com/heavycoinnews
redditurl: http://www.reddit.com/r/heavycoin
facebookurl: https://www.facebook.com/Heavycoin
